name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Setup Dependencies
        run: sudo apt-get -y install libpcap-dev golang git
           
        

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          wget https://github.com/veo/vscan/releases/download/v2.1.0/vscan_2.1.0_linux_amd64.zip
          mkdir vscan
          mv vscan_2.1.0_linux_amd64.zip ./vscan
          cd vscan
          unzip vscan_2.1.0_linux_amd64.zip
          cp vscan /usr/local/bin/vscan
          
        shell: bash


      - name: Running naabu to check top all ports
        run: |
          vscan -host 210.46.97.0/24
        shell: bash


      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt -title
          httpx -l output/active_ports.txt | tee output/active_urls.txt
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/active_ports.txt
          git add output/active_urls.txt
      - name: Commit results to Github
        run: |
          git config --local user.email "admin@inbug.org"
          git config --global user.name "inbug-team"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
